// <auto-generated />
using BasicShop.DataAccess.Concrete.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BasicShop.DataAccess.Migrations
{
    [DbContext(typeof(BasicShopContext))]
    [Migration("20190713091057_InserSomeData")]
    partial class InserSomeData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview6.19304.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BasicShop.Entity.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Smart phone"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Laptop"
                        });
                });

            modelBuilder.Entity("BasicShop.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId");

                    b.Property<string>("ProductName");

                    b.Property<decimal>("UnitPrice");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            ProductName = "LG G4",
                            UnitPrice = 2500m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            ProductName = "IPhone 7",
                            UnitPrice = 5000m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            ProductName = "Dell 9570",
                            UnitPrice = 13000m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            ProductName = "Lenovo Yoga 530",
                            UnitPrice = 4700m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            ProductName = "Lenovo X270",
                            UnitPrice = 6800m
                        });
                });

            modelBuilder.Entity("BasicShop.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
